### ISSUE TITLE
How to hex input for SHA256 library ?

### ISSUE THREAD

**Issue by trapdoor26** [CSSHL/ESP8266-Arduino-cryptolibs#2]
Hello,

I would like to use your lib for a project with NodeMCU 1.0 but I need to give 16 bytes of hex values as an input to the sha256 algorithm.

I understand from the example that text can be an input form but I could not find out how to modify the code to make it compatible for hex input.

Thanks for your help :)

**Comment by NdK73** [comment]
Depending on your use case, you can hash the string (it might include the trailing NUL byte or not) or the binary buffer obtained by decoding the hex string.
In the former case, you can use the string as-is, in the latter you have to convert it to a buffer and then pass that buffer to the hash function. If you need an example of a crude in-place hex2char decoder, you can refer to https://github.com/NdK73/Domotic/blob/master/src/Domotic.cpp#L1164 .

**Comment by trapdoor26** [comment]
Ndk73 thanks for reply but i tried converting hex to char earlier but my source sends hex values so not always input bytes corresponds to a ASCII value. So i am stuck at that point. 
And also i need to send back to the source the output after hashing and i need to send it also as hex (bytes)

**Comment by NdK73** [comment]
You have to convert the string containing hex-encoded bytes (2 symbols per byte) to a raw byte array (containing the exact bytes that were encoded), then pass that byte array to the hash function. The len of the byte array will always be half the string len (not including the string's terminator NUL byte). That's what **hex2uint8()** does.
After hashing the byte array, you might need to re-encode the hash value (a byte array) to hex values to be sent. That's easily done with a for(...) printf("%02x", *p) or similar.
If you look at the linked file, you'll see two helper methods to encode and decode using base64 (more space-efficient for buffers longer than a few bytes).
But that's not an issue with the library, just standard programming.
